apiVersion: cilium.io/v2
kind: CiliumEnvoyConfig
metadata:
  name: envoy-timeout-cart
  namespace: otel-demo
spec:
  resources:
    - '@type': type.googleapis.com/envoy.config.listener.v3.Listener
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                value:
                  stat_prefix: ingress_http
                  common_http_protocol_options:
                    idle_timeout: 900ms

  services:
    - name: opentelemetry-demo-cartservice
      namespace: otel-demo
---
apiVersion: cilium.io/v2
kind: CiliumEnvoyConfig
metadata:
  name: envoy-timeout-product
  namespace: otel-demo
spec:
  resources:
    - '@type': type.googleapis.com/envoy.config.listener.v3.Listener
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                value:
                  stat_prefix: ingress_http
                  common_http_protocol_options:
                      idle_timeout: 900ms

  services:
    - name: opentelemetry-demo-productcatalogservice
      namespace: otel-demo