apiVersion: batch/v1
kind: CronJob
metadata:
  name: loadtestservice
  labels:
    app.kubernetes.io/component: loadtest
    app.kubernetes.io/part-of: booking
    app.kubernetes.io/name: loadtest
    app.kubernetes.io/version: "1.0.0"
    dt.owner: booking
spec:
  schedule: "55 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: loadtest
            product: k6
            app.kubernetes.io/instance: booking
            app.kubernetes.io/component: loadtest
            app.kubernetes.io/part-of: booking
            app.kubernetes.io/name: loadtest
            app.kubernetes.io/version: "1.0.0"
            sidecar.istio.io/inject: "false"
            dt.owner: booking
          annotations:
            oneagent.dynatrace.com/inject: "false"
            app.kubernetes.io/part-of: booking
            app.kubernetes.io/name: loadtest
            app.kubernetes.io/version: "1.0.0"
            sidecar.istio.io/inject: "false"
        spec:
          terminationGracePeriodSeconds: 5
          restartPolicy: OnFailure
          containers:
            - name: k6load
              image: hrexed/bookinfo-load:1.2
              imagePullPolicy: Always
              args: [ "-u", "50", "-d", "59m" ]
              env:
                - name: FRONTEND_ADDR
                  value: "productpage:9080"
                - name: K6_DYNATRACE_URL
                  valueFrom:
                    secretKeyRef:
                      name: dynatrace
                      key: dynatrace_oltp_url
                - name: K6_DYNATRACE_INSECURE_SKIP_TLS_VERIFY
                  value: "true"
                - name: K6_DYNATRACE_APITOKEN
                  valueFrom:
                    secretKeyRef:
                      name: dynatrace
                      key: dt_api_token
              resources:
                requests:
                  cpu: 100m
                  memory: 128Mi
                limits:
                  cpu: 200m
                  memory: 256Mi