source 'https://rubygems.org'

gem "webrick", "~> 1.7"
gem 'json', '~> 2.7'
# OpenTelemetry dependencies
gem 'opentelemetry-sdk', '~> 1.9'
gem 'opentelemetry-exporter-otlp',  '~> 0.30'
gem 'opentelemetry-api' ,  '~> 1.7'
gem 'opentelemetry-instrumentation-all', '~> 0.84.0'
gem 'opentelemetry-instrumentation-http', '~> 0.26'
gem 'opentelemetry-instrumentation-net_http', '~> 0.25'
gem 'opentelemetry-propagator-b3', '~> 0.22.0'