source 'https://rubygems.org'

gem "webrick", "~> 1.7"
gem 'json', '~> 2.7'
# OpenTelemetry dependencies
gem 'opentelemetry-sdk', '~> 1.9'
gem 'opentelemetry-exporter-otlp', '~> 0.29'
gem 'opentelemetry-instrumentation-all', '~> 0.78'
