apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel
  labels:
    app: opentelemetry
    app.kubernetes.io/component: otel-statefullset
spec:
  mode: statefulset
  replicas: 1
  serviceAccount: otelcontribcol
  image: otel/opentelemetry-collector-contrib:0.133.0
  observability:
    metrics:
      enableMetrics: true
  env:
    - name: MY_POD_IP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.podIP
    - name: K8S_NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: DT_ENDPOINT
      valueFrom:
        secretKeyRef:
          name: dynatrace
          key: dynatrace_oltp_url
    - name: DT_API_TOKEN
      valueFrom:
        secretKeyRef:
          name: dynatrace
          key: dt_api_token
    - name: CLUSTERNAME
      valueFrom:
        secretKeyRef:
          name: dynatrace
          key: clustername
    - name: OTEL_SERVICE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.labels['app.kubernetes.io/component']
    - name: OTEL_RESOURCE_ATTRIBUTES
      value: service.name=$(OTEL_SERVICE_NAME)
  config:
    receivers:


      k8sobjects:
        auth_type: serviceAccount
        objects:
          - name: pods
            mode: pull
            interval: 10m
          - name: events
            mode: watch
      prometheus:
        config:
          scrape_configs:
            - job_name: opentelemetry-collector
              scrape_interval: 5s
              static_configs:
                - targets:
                    - ${MY_POD_IP}:8888
            - job_name: kgateway-gateways
              honor_labels: true
              kubernetes_sd_configs:
                - role: pod
              relabel_configs:
                - action: keep
                  regex: kube-gateway
                  source_labels:
                    - __meta_kubernetes_pod_label_kgateway
                - source_labels: [ __meta_kubernetes_pod_annotation_prometheus_io_scrape ]
                  action: keep
                  regex: true
                - source_labels: [ __meta_kubernetes_pod_annotation_prometheus_io_path ]
                  action: replace
                  target_label: __metrics_path__
                  regex: (.+)
                - action: replace
                  source_labels:
                    - __meta_kubernetes_pod_ip
                    - __meta_kubernetes_pod_annotation_prometheus_io_port
                  separator: ':'
                  target_label: __address__
                - action: labelmap
                  regex: __meta_kubernetes_pod_label_(.+)
                - source_labels: [ __meta_kubernetes_namespace ]
                  action: replace
                  target_label: kube_namespace
                - source_labels: [ __meta_kubernetes_pod_name ]
                  action: replace
                  target_label: pod
            - job_name: kgateway-controlplane
              honor_labels: true
              kubernetes_sd_configs:
                - role: pod
              relabel_configs:
                - action: keep
                  regex: kgateway
                  source_labels:
                    - __meta_kubernetes_pod_label_kgateway
                - source_labels: [ __meta_kubernetes_pod_annotation_prometheus_io_scrape ]
                  action: keep
                  regex: true
                - source_labels: [ __meta_kubernetes_pod_annotation_prometheus_io_path ]
                  action: replace
                  target_label: __metrics_path__
                  regex: (.+)
                - action: replace
                  source_labels:
                    - __meta_kubernetes_pod_ip
                    - __meta_kubernetes_pod_annotation_prometheus_io_port
                  separator: ':'
                  target_label: __address__
                - action: labelmap
                  regex: __meta_kubernetes_pod_label_(.+)
                - source_labels: [ __meta_kubernetes_namespace ]
                  action: replace
                  target_label: kube_namespace
                - source_labels: [ __meta_kubernetes_pod_name ]
                  action: replace
                  target_label: pod
            - job_name: 'linkerd-controller'
              kubernetes_sd_configs:
                - role: pod
                  namespaces:
                    names:
                      - '{{.Values.linkerdNamespace}}'
                      - '{{.Values.namespace}}'
              relabel_configs:
                - source_labels:
                    - __meta_kubernetes_pod_container_port_name
                  action: keep
                  regex: admin-http
                - source_labels: [ __meta_kubernetes_pod_container_name ]
                  action: replace
                  target_label: component
            - job_name: 'linkerd-service-mirror'
              kubernetes_sd_configs:
                - role: pod
              relabel_configs:
                - source_labels:
                    - __meta_kubernetes_pod_label_linkerd_io_control_plane_component
                    - __meta_kubernetes_pod_container_port_name
                  action: keep
                  regex: linkerd-service-mirror;admin-http$
                - source_labels: [ __meta_kubernetes_pod_container_name ]
                  action: replace
                  target_label: component
            - job_name: 'linkerd-proxy'
              kubernetes_sd_configs:
                - role: pod
              relabel_configs:
                - source_labels:
                    - __meta_kubernetes_pod_container_name
                    - __meta_kubernetes_pod_container_port_name
                    - __meta_kubernetes_pod_label_linkerd_io_control_plane_ns
                  action: keep
                  regex: ^{{default .Values.proxyContainerName "linkerd-proxy" .Values.proxyContainerName}};linkerd-admin;{{.Values.linkerdNamespace}}$
                - source_labels: [ __meta_kubernetes_namespace ]
                  action: replace
                  target_label: namespace
                - source_labels: [ __meta_kubernetes_pod_name ]
                  action: replace
                  target_label: pod
                # special case k8s' "job" label, to not interfere with prometheus' "job"
                # label
                # __meta_kubernetes_pod_label_linkerd_io_proxy_job=foo =>
                # k8s_job=foo
                - source_labels: [ __meta_kubernetes_pod_label_linkerd_io_proxy_job ]
                  action: replace
                  target_label: k8s_job
                # drop __meta_kubernetes_pod_label_linkerd_io_proxy_job
                - action: labeldrop
                  regex: __meta_kubernetes_pod_label_linkerd_io_proxy_job
                # __meta_kubernetes_pod_label_linkerd_io_proxy_deployment=foo =>
                # deployment=foo
                - action: labelmap
                  regex: __meta_kubernetes_pod_label_linkerd_io_proxy_(.+)
                # drop all labels that we just made copies of in the previous labelmap
                - action: labeldrop
                  regex: __meta_kubernetes_pod_label_linkerd_io_proxy_(.+)
                # __meta_kubernetes_pod_label_linkerd_io_foo=bar =>
                # foo=bar
                - action: labelmap
                  regex: __meta_kubernetes_pod_label_linkerd_io_(.+)
                # Copy all pod labels to tmp labels
                - action: labelmap
                  regex: __meta_kubernetes_pod_label_(.+)
                  replacement: __tmp_pod_label_$1
                # Take `linkerd_io_` prefixed labels and copy them without the prefix
                - action: labelmap
                  regex: __tmp_pod_label_linkerd_io_(.+)
                  replacement: __tmp_pod_label_$1
                # Drop the `linkerd_io_` originals
                - action: labeldrop
                  regex: __tmp_pod_label_linkerd_io_(.+)
                # Copy tmp labels into real labels
                - action: labelmap
                  regex: __tmp_pod_label_(.+)
            - job_name: kubernetes-pods
              kubernetes_sd_configs:
                  - role: pod
              relabel_configs:
                - action: keep
                  regex: true
                  source_labels:
                    - __meta_kubernetes_pod_annotation_prometheus_io_scrape
                - action: replace
                  regex: (https?)
                  source_labels:
                    - __meta_kubernetes_pod_annotation_prometheus_io_scheme
                  target_label: __scheme__
                - action: replace
                  regex: (.+)
                  source_labels:
                    - __meta_kubernetes_pod_annotation_prometheus_io_path
                  target_label: __metrics_path__
                - action: replace
                  regex: ([^:]+)(?::\d+)?;(\d+)
                  replacement: $1:$2
                  source_labels:
                    - __address__
                    - __meta_kubernetes_pod_annotation_prometheus_io_port
                  target_label: __address__
                - action: labelmap
                  regex: __meta_kubernetes_pod_label_(.+)
                - action: replace
                  source_labels:
                    - __meta_kubernetes_namespace
                  target_label: kubernetes_namespace
                - action: replace
                  source_labels:
                    - __meta_kubernetes_pod_name
                  target_label: kubernetes_pod_name
                - action: drop
                  regex: Pending|Succeeded|Failed
                  source_labels:
                    - __meta_kubernetes_pod_phase

      otlp:
        protocols:
          grpc:
            endpoint: ${MY_POD_IP}:4317
          http:
            cors:
              allowed_origins:
                - http://*
                - https://*
            endpoint: ${MY_POD_IP}:4318

    processors:
      batch:
        send_batch_max_size: 1000
        timeout: 30s
        send_batch_size : 800

      memory_limiter:
        check_interval: 1s
        limit_percentage: 70
        spike_limit_percentage: 30

      cumulativetodelta: {}

      k8sattributes/k8S:
        extract:
          metadata:
            - k8s.cluster.uid
        pod_association:
          - sources:
              - from: resource_attribute
                name: k8s.namespace.name
      k8sattributes:
        extract:
          metadata:
            - k8s.pod.name
            - k8s.pod.uid
            - k8s.deployment.name
            - k8s.statefulset.name
            - k8s.daemonset.name
            - k8s.cronjob.name
            - k8s.namespace.name
            - k8s.container.name
            - k8s.node.name
            - k8s.cluster.uid
        pod_association:
          - sources:
              - from: resource_attribute
                name: k8s.pod.name
              - from: resource_attribute
                name: k8s.namespace.name
          - sources:
              - from: resource_attribute
                name: k8s.pod.ip
          - sources:
              - from: resource_attribute
                name: k8s.pod.uid
          - sources:
              - from: connection
      resource:
        attributes:
          - key: k8s.cluster.name
            value: ${CLUSTERNAME}
            action: insert




      transform:
        error_mode: ignore
        log_statements:
          - context: resource
            statements:
              - set(attributes["dt.kubernetes.workload.kind"], "statefulset") where IsString(attributes["k8s.statefulset.name"])
              - set(attributes["dt.kubernetes.workload.name"], attributes["k8s.statefulset.name"]) where IsString(attributes["k8s.statefulset.name"])
              - set(attributes["dt.kubernetes.workload.kind"], "deployment") where IsString(attributes["k8s.deployment.name"])
              - set(attributes["dt.kubernetes.workload.name"], attributes["k8s.deployment.name"]) where IsString(attributes["k8s.deployment.name"])
              - set(attributes["dt.kubernetes.workload.kind"], "daemonset") where IsString(attributes["k8s.daemonset.name"])
              - set(attributes["dt.kubernetes.workload.name"], attributes["k8s.daemonset.name"]) where IsString(attributes["k8s.daemonset.name"])
              - set(attributes["dt.kubernetes.cluster.id"], attributes["k8s.cluster.uid"]) where IsString(attributes["k8s.cluster.uid"])

        trace_statements:
          - context: resource
            statements:
              - set(attributes["dt.kubernetes.workload.kind"], "statefulset") where IsString(attributes["k8s.statefulset.name"])
              - set(attributes["dt.kubernetes.workload.name"], attributes["k8s.statefulset.name"]) where IsString(attributes["k8s.statefulset.name"])
              - set(attributes["dt.kubernetes.workload.kind"], "deployment") where IsString(attributes["k8s.deployment.name"])
              - set(attributes["dt.kubernetes.workload.name"], attributes["k8s.deployment.name"]) where IsString(attributes["k8s.deployment.name"])
              - set(attributes["dt.kubernetes.workload.kind"], "daemonset") where IsString(attributes["k8s.daemonset.name"])
              - set(attributes["dt.kubernetes.workload.name"], attributes["k8s.daemonset.name"]) where IsString(attributes["k8s.daemonset.name"])
              - set(attributes["dt.kubernetes.cluster.id"], attributes["k8s.cluster.uid"]) where IsString(attributes["k8s.cluster.uid"])

        metric_statements:
          - context: resource
            statements:
              - set(attributes["dt.kubernetes.workload.kind"], "statefulset") where IsString(attributes["k8s.statefulset.name"])
              - set(attributes["dt.kubernetes.workload.name"], attributes["k8s.statefulset.name"]) where IsString(attributes["k8s.statefulset.name"])
              - set(attributes["dt.kubernetes.workload.kind"], "deployment") where IsString(attributes["k8s.deployment.name"])
              - set(attributes["dt.kubernetes.workload.name"], attributes["k8s.deployment.name"]) where IsString(attributes["k8s.deployment.name"])
              - set(attributes["dt.kubernetes.workload.kind"], "daemonset") where IsString(attributes["k8s.daemonset.name"])
              - set(attributes["dt.kubernetes.workload.name"], attributes["k8s.daemonset.name"]) where IsString(attributes["k8s.daemonset.name"])
              - set(attributes["dt.kubernetes.cluster.id"], attributes["k8s.cluster.uid"]) where IsString(attributes["k8s.cluster.uid"])

      cumulativetodelta: {}



    exporters:

      loadbalancing:
        routing_key: "service"
        protocol:
          otlp:
            # all options from the OTLP exporter are supported
            # except the endpoint
            timeout: 1s
            tls:
              insecure: true
        resolver:
          # use k8s service resolver, if collector runs in kubernetes environment
          k8s:
            service: otelback-collector.default
      loadbalancing/metrics:
        routing_key: "metric"
        protocol:
          otlp:
            # all options from the OTLP exporter are supported
            # except the endpoint
            timeout: 1s
            tls:
              insecure: true
        resolver:
          # use k8s service resolver, if collector runs in kubernetes environment
          k8s:
            service: otelback-collector.default
      otlphttp:
        endpoint: ${DT_ENDPOINT}/api/v2/otlp
        headers:
          Authorization: "Api-Token ${DT_API_TOKEN}"
        timeout: 10s  # Increase significantly
        retry_on_failure:
          enabled: true
          initial_interval: 5s
          max_interval: 30s
          max_elapsed_time: 300s
        sending_queue:
          enabled: true
          num_consumers: 10
          queue_size: 5000
      debug:
        verbosity: detailed

    connectors:
      spanmetrics:
        exemplars:
          enabled: true
        aggregation_temporality: "AGGREGATION_TEMPORALITY_DELTA"



    service:
      pipelines:

        traces:
          receivers: [otlp]
          processors: [memory_limiter,k8sattributes,transform,batch]
          exporters: [spanmetrics,otlphttp]
        metrics:
          receivers: [otlp,prometheus]
          processors: [memory_limiter,k8sattributes,transform,cumulativetodelta,batch]
          exporters: [otlphttp]
        metrics/span:
          receivers: [ spanmetrics ]
          exporters: [ otlphttp ]
        logs:
          receivers: [otlp]
          processors: [memory_limiter,k8sattributes,transform,resource,batch]
          exporters: [otlphttp]

      telemetry:
        metrics:
          readers:
            - pull:
                exporter:
                  prometheus:
                    host: ${MY_POD_IP}
                    port: 8888
                    without_units: true
        traces:
          processors:
            - batch:
                exporter:
                  otlp:
                    protocol: grpc
                    endpoint: http://localhost:4317

