apiVersion: kuma.io/v1alpha1
kind: MeshGatewayConfig
metadata:
  name: fixed-nodeport-config
  namespace: kuma-system
spec:
  serviceType: NodePort
  serviceTemplate:
    spec:
      ports:
        - name: http-80
          port: 80
          nodePort: 30080
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: kuma
spec:
  controllerName: gateways.kuma.io/controller
  parametersRef:
    group: kuma.io
    kind: MeshGatewayConfig
    name: fixed-nodeport-config