apiVersion: gateway.kgateway.dev/v1alpha1
kind: TrafficPolicy
metadata:
  name: reviews-traffic-policy
  namespace: booking
spec:
  # Connection pool settings (rate limiting at connection level)
  rateLimit:
    local:
      tokenBucket:
        maxTokens: 50
        tokensPerFill: 10
        fillInterval: 60s





---
# ============================================
# TrafficPolicy: Rate Limiting, Timeouts for details
# ============================================
apiVersion: gateway.kgateway.dev/v1alpha1
kind: TrafficPolicy
metadata:
  name: details-traffic-policy
  namespace: booking
spec:
  rateLimit:
    local:
      tokenBucket:
        maxTokens: 50
        tokensPerFill: 10
        fillInterval: 60s


